name: Ci cd

on:
  push:
    branches: ["main"]
env:
  REGISTRY: ghcr.io
  CLIENT_IMAGE_NAME: emenu124ru/client:latest
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: eslint
        run: yarn lint
  publish:
    name: publish react image
    needs: [ linters ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Build and Publish
        run: |
          docker build --tag ${{ env.REGISTRY }}/${{ env.CLIENT_IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.CLIENT_IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - uses: actions/checkout@v1

      - name: Executing remote command
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            bash build-client-frontend.sh
